baseURL = "https://surrealmint.github.io/"
languageCode = "en-us"
title = "analogarden"
theme = ""
pygmentsCodeFences = true
pygmentsStyle = "monokai"

# Main menu navigation
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4

[params]
  # Your name
  author = "surrealmint"
  # A short description of you
  description = "mechatronics undergrad"
